version: '3.9'

services:

    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq
        hostname: rabbitmq
        volumes:
            - ./.docker/rabbitmq/etc/:/usr/share/etc/rabbitmq/
            - ./.docker/rabbitmq/data/:/usr/share/var/lib/rabbitmq/
            - ./.docker/rabbitmq/logs/:/usr/share/var/log/rabbitmq/
        environment:
            RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
            RABBITMQ_DEFAULT_USER: rabbit
            RABBITMQ_DEFAULT_PASS: rabbit
        ports:
            - "5672:5672"
            - "15672:15672"